In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
apple_file = "AppleStore.csv"
apple_df = pd.read_csv(apple_file)
apple_df.head()

,Unnamed: 0,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
0,1,281656475,PAC-MAN Premium,100788224,USD,3.99,21292,26,4.0,4.5,6.3.5,4+,Games,38,5,10,1
1,2,281796108,Evernote - stay organized,158578688,USD,0.00,161065,26,4.0,3.5,8.2.2,4+,Productivity,37,5,23,1
2,3,281940292,"WeatherBug - Local Weather, Radar, Maps, Alerts",100524032,USD,0.00,188583,2822,3.5,4.5,5.0.0,4+,Weather,37,5,3,1
3,4,282614216,"eBay: Best App to Buy, Sell, Save! Online Shop...",128512000,USD,0.00,262241,649,4.0,4.5,5.10.0,12+,Shopping,37,5,9,1
4,5,282935706,Bible,92774400,USD,0.00,985920,5320,4.5,5.0,7.5.1,4+,Reference,37,5,45,1

In [4]:
new_apple_df=apple_df[['track_name', 'price', 'rating_count_tot', 'prime_genre', 'user_rating' ]].copy()
new_apple_df.head()

,track_name,price,rating_count_tot,prime_genre,user_rating
0,PAC-MAN Premium,3.99,21292,Games,4.0
1,Evernote - stay organized,0.00,161065,Productivity,4.0
2,"WeatherBug - Local Weather, Radar, Maps, Alerts",0.00,188583,Weather,3.5
3,"eBay: Best App to Buy, Sell, Save! Online Shop...",0.00,262241,Shopping,4.0
4,Bible,0.00,985920,Reference,4.5

In [5]:
apple_transf = new_apple_df.rename(columns={"track_name": "App",
                                                          "price": "Price",
                                                          "rating_count_tot": "Reviews",
                                                           "prime_genre":"Genres",
                                                            "user_rating":"Rating"})
apple_transf.head()

,App,Price,Reviews,Genres,Rating
0,PAC-MAN Premium,3.99,21292,Games,4.0
1,Evernote - stay organized,0.00,161065,Productivity,4.0
2,"WeatherBug - Local Weather, Radar, Maps, Alerts",0.00,188583,Weather,3.5
3,"eBay: Best App to Buy, Sell, Save! Online Shop...",0.00,262241,Shopping,4.0
4,Bible,0.00,985920,Reference,4.5

In [6]:
google_file = "googleplaystore.csv"
google_df = pd.read_csv(google_file)
google_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [7]:
new_google_df=google_df[['App', 'Price', 'Reviews','Genres', 'Rating' ]].copy()
new_google_df.head()

,App,Price,Reviews,Genres,Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,0,159,Art & Design,4.1
1,Coloring book moana,0,967,Art & Design;Pretend Play,3.9
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",0,87510,Art & Design,4.7
3,Sketch - Draw & Paint,0,215644,Art & Design,4.5
4,Pixel Draw - Number Art Coloring Book,0,967,Art & Design;Creativity,4.3

In [14]:
merge_df=pd.merge(new_google_df, apple_transf, on="App", how="inner")
merge_df

,App,Price_x,Reviews_x,Genres_x,Rating_x,Price_y,Reviews_y,Genres_y,Rating_y
0,Infinite Painter,0,36815,Art & Design,4.1,0.00,65,Productivity,4.0
1,Indeed Job Search,0,674730,Business,4.3,0.00,38681,Business,4.0
2,Uber Driver,0,1254730,Business,4.4,0.00,3289,Business,3.0
3,ADP Mobile Solutions,0,85185,Business,4.3,0.00,8324,Business,4.0
4,WhatsApp Messenger,0,69119316,Communication,4.4,0.00,287589,Social Networking,4.5
...,...,...,...,...,...,...,...,...,...
548,Talking Tom Bubble Shooter,0,687136,Casual,4.4,0.00,2659,Games,4.5
549,Crazy Freekick,0,47688,Sports,3.9,0.00,228,Games,4.5
550,Fruit Ninja Classic,$0.99,85468,Arcade,4.3,1.99,698516,Games,4.5
551,"sugar, sugar",$1.20,1405,Puzzle,4.2,0.99,139,Games,4.5
552,Fuel Rewards® program,0,32433,Lifestyle,4.6,0.00,2249,Shopping,4.5

In [25]:
new_df=merge_df.rename(columns={"Price_x": "Google Price", "Reviews_x": "Google Review",
                            "Genres_x": "Google Genre", "Rating_x":"Google Rating",
                            "Price_y": "Apple Price", "Reviews_y": "Apple Review",
                            "Genres_y": "Apple Genre", "Rating_y":"Apple Rating"})

In [18]:
# new_df = pd.merge(new_google_df, apple_transf,  how='inner', left_on=['App','Genres'], right_on = ['App','Genres'])
# new_df

In [27]:
free_apple_df = new_df.loc[new_df["Apple Price"] == 0.00, :]
free_apple_df

,App,Google Price,Google Review,Google Genre,Google Rating,Apple Price,Apple Review,Apple Genre,Apple Rating
0,Infinite Painter,0,36815,Art & Design,4.1,0.0,65,Productivity,4.0
1,Indeed Job Search,0,674730,Business,4.3,0.0,38681,Business,4.0
2,Uber Driver,0,1254730,Business,4.4,0.0,3289,Business,3.0
3,ADP Mobile Solutions,0,85185,Business,4.3,0.0,8324,Business,4.0
4,WhatsApp Messenger,0,69119316,Communication,4.4,0.0,287589,Social Networking,4.5
...,...,...,...,...,...,...,...,...,...
546,Messenger,0,68025,Social,4.1,0.0,351466,Social Networking,3.0
547,Angry Birds Space HD,0,43645,Arcade,4.5,0.0,39502,Games,4.0
548,Talking Tom Bubble Shooter,0,687136,Casual,4.4,0.0,2659,Games,4.5
549,Crazy Freekick,0,47688,Sports,3.9,0.0,228,Games,4.5
552,Fuel Rewards® program,0,32433,Lifestyle,4.6,0.0,2249,Shopping,4.5

In [31]:
rating_google_df = new_df.loc[new_df["Google Rating"] > 4, :]
rating_google_df

,App,Google Price,Google Review,Google Genre,Google Rating,Apple Price,Apple Review,Apple Genre,Apple Rating
0,Infinite Painter,0,36815,Art & Design,4.1,0.00,65,Productivity,4.0
1,Indeed Job Search,0,674730,Business,4.3,0.00,38681,Business,4.0
2,Uber Driver,0,1254730,Business,4.4,0.00,3289,Business,3.0
3,ADP Mobile Solutions,0,85185,Business,4.3,0.00,8324,Business,4.0
4,WhatsApp Messenger,0,69119316,Communication,4.4,0.00,287589,Social Networking,4.5
...,...,...,...,...,...,...,...,...,...
547,Angry Birds Space HD,0,43645,Arcade,4.5,0.00,39502,Games,4.0
548,Talking Tom Bubble Shooter,0,687136,Casual,4.4,0.00,2659,Games,4.5
550,Fruit Ninja Classic,$0.99,85468,Arcade,4.3,1.99,698516,Games,4.5
551,"sugar, sugar",$1.20,1405,Puzzle,4.2,0.99,139,Games,4.5
552,Fuel Rewards® program,0,32433,Lifestyle,4.6,0.00,2249,Shopping,4.5

In [32]:
rating_apple_df = new_df.loc[new_df["Apple Rating"] > 4, :]
rating_apple_df

,App,Google Price,Google Review,Google Genre,Google Rating,Apple Price,Apple Review,Apple Genre,Apple Rating
4,WhatsApp Messenger,0,69119316,Communication,4.4,0.00,287589,Social Networking,4.5
5,WhatsApp Messenger,0,69119316,Communication,4.4,0.00,287589,Social Networking,4.5
6,WhatsApp Messenger,0,69109672,Communication,4.4,0.00,287589,Social Networking,4.5
14,WeChat,0,5387333,Communication,4.2,0.00,34584,Social Networking,4.5
15,WeChat,0,5387446,Communication,4.2,0.00,34584,Social Networking,4.5
...,...,...,...,...,...,...,...,...,...
548,Talking Tom Bubble Shooter,0,687136,Casual,4.4,0.00,2659,Games,4.5
549,Crazy Freekick,0,47688,Sports,3.9,0.00,228,Games,4.5
550,Fruit Ninja Classic,$0.99,85468,Arcade,4.3,1.99,698516,Games,4.5
551,"sugar, sugar",$1.20,1405,Puzzle,4.2,0.99,139,Games,4.5
552,Fuel Rewards® program,0,32433,Lifestyle,4.6,0.00,2249,Shopping,4.5

In [35]:
free_google_df = new_df.loc[new_df["Google Price"] > 1, :]
free_google_df

TypeError: '>' not supported between instances of 'str' and 'int'