In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
file = "./app_table.csv"
apps_df = pd.read_csv(file)
apps_df

,index,app,price,reviews,genres,rating,os
0,324,- Free Comics - Comic Apps,0,115,Comics,3.5,Android
1,5523,-The 穴通し3D- 君の記憶力x反射神経を問う! ～Mr.CURVEからの挑戦状 ～,0.0,0,Games,0.0,Apple
2,2705,! OH Fantastic Free Kick + Kick Wall Challenge,0.0,0,Games,0.0,Apple
3,3551,( OFFTIME ) light – Track how much you use you...,2.99,22,Health & Fitness,2.0,Apple
4,6666,*Solitaire*,0.0,460,Games,4.5,Apple
...,...,...,...,...,...,...,...
18033,6178,鴨川等間隔の法則,0.0,0,Games,0.0,Apple
18034,4013,麻雀物語３ 役満乱舞の究極大戦,9.99,0,Games,0.0,Apple
18035,3426,黄金日-贵金属理财投资黄金白银,0.0,0,Finance,0.0,Apple
18036,5986,龙之觉醒-热血经典RPG，回味激燃岁月,0.0,0,Games,0.0,Apple
18037,3728,龙珠直播-高清游戏娱乐直播平台,0.0,0,Entertainment,0.0,Apple

In [3]:
new_df = apps_df.rename(columns={"index": "id",
                                                          "app": "App", 
                                                          "price": "Price",
                                                           "reviews":"Total_Ratings",
                                                            "genres":"Genre", "rating":"User_Rating", "os":"OS"})
new_df.head()

,id,App,Price,Total_Ratings,Genre,User_Rating,OS
0,324,- Free Comics - Comic Apps,0,115,Comics,3.5,Android
1,5523,-The 穴通し3D- 君の記憶力x反射神経を問う! ～Mr.CURVEからの挑戦状 ～,0.0,0,Games,0.0,Apple
2,2705,! OH Fantastic Free Kick + Kick Wall Challenge,0.0,0,Games,0.0,Apple
3,3551,( OFFTIME ) light – Track how much you use you...,2.99,22,Health & Fitness,2.0,Apple
4,6666,*Solitaire*,0.0,460,Games,4.5,Apple

In [4]:
new_df.set_index("id", inplace=True)

In [5]:
new_df

,App,Price,Total_Ratings,Genre,User_Rating,OS
id,,,,,,
324,- Free Comics - Comic Apps,0,115,Comics,3.5,Android
5523,-The 穴通し3D- 君の記憶力x反射神経を問う! ～Mr.CURVEからの挑戦状 ～,0.0,0,Games,0.0,Apple
2705,! OH Fantastic Free Kick + Kick Wall Challenge,0.0,0,Games,0.0,Apple
3551,( OFFTIME ) light – Track how much you use you...,2.99,22,Health & Fitness,2.0,Apple
6666,*Solitaire*,0.0,460,Games,4.5,Apple
...,...,...,...,...,...,...
6178,鴨川等間隔の法則,0.0,0,Games,0.0,Apple
4013,麻雀物語３ 役満乱舞の究極大戦,9.99,0,Games,0.0,Apple
3426,黄金日-贵金属理财投资黄金白银,0.0,0,Finance,0.0,Apple
5986,龙之觉醒-热血经典RPG，回味激燃岁月,0.0,0,Games,0.0,Apple
3728,龙珠直播-高清游戏娱乐直播平台,0.0,0,Entertainment,0.0,Apple

In [6]:
# apps_db = apps_df[['app', 'price', 'reviews', 'genres', 'rating', 'os']].copy()
# apps_db.head()

In [7]:
# df = apps_db.reset_index()
# df

In [8]:
# new_df = df.rename(columns={"index": "ID",
#                                                           "app": "App", 
#                                                           "price": "Price",
#                                                            "reviews":"Total_Ratings",
#                                                             "genres":"Genre", "rating":"User_Rating", "os":"OS"})
# new_df.head()

In [9]:
rds_connection_string = "postgres:postgres@localhost:5432/apps_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [10]:
engine.table_names()

['final_apps', 'new_apps_db', 'apple_google_apps']

In [13]:
new_df.to_sql(name='final_apps', con=engine, if_exists='replace', index=True)

In [ ]:
# new_df.to_csv('final_app.csv', index=False)

In [ ]:
# final_app.to_sql('final_apps.sql')